### ISSUE TITLE
start_clp.py start_webui() does not add a docker port binding

### ISSUE THREAD

**Issue by Meai** [y-scope/clp#479]
### Bug

**Problem:** 
The webui inside the clp-webui container can't be reached

**Attempts to fix:**
Uncommenting and changing the web ui port here does nothing: etc/clp-config.yml

**Suggested solution:**
Here,
https://github.com/y-scope/clp/blob/94d96d3e09b193d1a4658c79ffad257cbe3cd11d/components/clp-package-utils/clp_package_utils/scripts/start_clp.py#L694

add an equivalent `append_docker_port_settings_for_host_ips()`, method call just like the other methods already have that also respects the clp-config.yml

### CLP version

v0.1.1

### Environment

Opensuse Tumbleweed in Win11 WSL starting https://github.com/y-scope/clp/releases/download/v0.1.1/clp-json-ubuntu-focal-x86_64-v0.1.1.tar.gz

### Reproduction steps

wget https://github.com/y-scope/clp/releases/download/v0.1.1/clp-json-ubuntu-focal-x86_64-v0.1.1.tar.gz
tar xvfz https://github.com/y-scope/clp/releases/download/v0.1.1/clp-json-ubuntu-focal-x86_64-v0.1.1.tar.gz
cd clp-json-ubuntu-focal-x86_64-v0.1.1/sbin
./start-clp.sh

**Comment by junhaoliao** [comment]
Hey @Meai ,

Thanks for the issue report. 

# Reference steps

We tried clean installing OpenSUSE Tumbleweed in Win11 WSL and was able to configure the WebUI port, run the clp-package as a non-root user, and access the WebUI on the desired port in a browser. Here's what we did:
1. Install OpenSUSE Tumbleweed from Microsoft Store.
2. Open "OpenSUSE Tumbleweed" and went through the initialization wizard with a password set.
3. Due to by default sysmtemd isnot enabled for OpenSUSE Tumbleweed WSL which `docker` requires, enable systemd by editing (adding) a WSL config file `/etc/wsl.conf`:
   ```
   [boot]
   systemd=true
   ```
4. `sudo zypper install python3 docker docker-compose docker-compose-switch`
5. ```
   # To enable current non-root user to use docker
   sudo usermod -G docker -a $USER

   # Log in to the docker group
   newgrp docker

   # Restart the docker daemon
   sudo systemctl restart docker
   ```
7. ```
   wget https://github.com/y-scope/clp/releases/download/v0.1.1/clp-json-ubuntu-focal-x86_64-v0.1.1.tar.gz
   tar xvf clp-json-ubuntu-focal-x86_64-v0.1.1.tar.gz
   ```
8. Change the webui port in `clp-json-ubuntu-focal-x86_64-v0.1.1/etc/clp-config.yml` to 4010. e.g.,
   ```
   # Note we have to uncomment the whole webui section
   webui:
       host: "localhost"
       port: 4010
       logging_level: "INFO"
   ```
9. Launch the CLP pakacge.
   ```
   cd clp-json-ubuntu-focal-x86_64-v0.1.1/sbin
   ./start-clp.sh
   ```
10. Access http://localhost:4010 from Microsoft Edge (a Chromium-based browser) and was able to see the webui:
   ![image](https://github.com/user-attachments/assets/a0d5bf5e-2062-420d-ba2a-e5e5043c0793)

# Debugging
If with above steps you're still observing the failure to launch webui on a desired port, to help us better understand the issue, may I ask you to provide the following:
1. The `clp-json-ubuntu-focal-x86_64-v0.1.1/etc/clp-config.yml`.
2. Just in case you haven't, kindly check if `docker run --rm hello-world` (without sudo or root) is reporting any error.
3. After you start `clp-json-ubuntu-focal-x86_64-v0.1.1/sbin/start-clp.sh`,
   1. The output of `docker ps` which shows you a list of running containers.
   2. Could you also tar the CLP package logs and send it as a attachment to a response on this thread or [info@yscope.com](mailto:info@yscope.com)? e.g.,
   ```
   tar czf clp-focal-logs-479-240713.tar.gz ./clp-json-ubuntu-focal-x86_64-v0.1.1/var/log
   ```

Many thanks in advance!

**Comment by Meai** [comment]
Okay, I was very surprised that this worked for you and after more debugging I finally found the right clue. It seems that `--network host` does not work by default on Docker Desktop for Windows and I had to update to the latest version and enable it first: 
![image](https://github.com/user-attachments/assets/6b8e382f-504f-4485-9ec6-9ab2fab0a785)

You must have enabled this at some point earlier I guess? But good to know this now.

**Comment by junhaoliao** [comment]
> Okay, I was very surprised that this worked for you and after more debugging I finally found the right clue. It seems that `--network host` does not work by default on Docker Desktop for Windows and I had to update to the latest version and enable it first: ![image](https://private-user-images.githubusercontent.com/649922/348458747-6b8e382f-504f-4485-9ec6-9ab2fab0a785.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA4NTg1MzcsIm5iZiI6MTcyMDg1ODIzNywicGF0aCI6Ii82NDk5MjIvMzQ4NDU4NzQ3LTZiOGUzODJmLTUwNGYtNDQ4NS05ZWM2LTlhYjJmYWIwYTc4NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxM1QwODEwMzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMWRkZWZlN2NkMmI1NjQ3NGQxMWRkZjIwNDNhN2VhYjYwNGY0N2NjZmJlNTk3Y2FiNTliZjkzMWZmZDliZDQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.95bQHPa_325ZN0_j2LQsm99CGkmF0dk_rUjbuHoHCB8)
> 
> You must have enabled this at some point earlier I guess? But good to know this now. Sadly I only got any kind of warning log when I tried to add the -p 4010:4010 manually to the .py file and attempted to start.

Ah. In my steps, the docker installation was purely done within the WSL terminal (without Docker Desktop), which might explain the configuration differences. We will have the docs updated in the future to better help everyone. Many thanks for quickly getting back to us and sharing the solution!
